/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "compute.h"
#include <stdio.h>


float
compute_1(char *host, float a, float b, char op)
{
	CLIENT *clnt;
	float  *result_1;
	values  add_1_arg;
	float  *result_2;
	values  sub_1_arg;
	float  *result_3;
	values  mul_1_arg;
	float  *result_4;
	values  div_1_arg;

	if(op=='+')
	{
		add_1_arg.num1 = a;
		add_1_arg.num2 = b;
		add_1_arg.operation = op;

		clnt = clnt_create (host, compute, compute_vers, "udp");
			if (clnt == NULL) {
				clnt_pcreateerror (host);
				exit (1);
			}

	result_1 = add_1(&add_1_arg, clnt);
		if (result_1 == (float *) NULL) {
			clnt_perror (clnt, "call failed");
		}
	clnt_destroy(clnt);
	return (*result_1);
	}
	else if (op == '-')
	{

	sub_1_arg.num1 = a;
	sub_1_arg.num2 = b;
	sub_1_arg.operation = op;

	clnt = clnt_create (host, compute, compute_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	result_2 = sub_1(&sub_1_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy(clnt);
	return (*result_2);
}
else if(op=='*')
{
	mul_1_arg.num1 = a;
	mul_1_arg.num2 = b;
	mul_1_arg.operation = op;

	clnt = clnt_create (host, compute, compute_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


	result_3 = mul_1(&mul_1_arg, clnt);
	if (result_3 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy(clnt);
	return (*result_3);
}
else if(op=='*')
{
	if (b==0)
	{
		printf("you are dividing by zero please put a valid number\n");
		exit(0);
	}
	div_1_arg.num1 = a;
	div_1_arg.num2 = b;
	div_1_arg.operation = op;

	clnt = clnt_create (host, compute, compute_vers, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	result_4 = div_1(&div_1_arg, clnt);
	if (result_4 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	clnt_destroy(clnt);
	return (*result_4);
}

}
int main (int argc, char *argv[])
{
	char *host;
	float num1, num2;
	char op;
	printf("enter two number followed by zero to perform:\n");
	scanf("%f",& num1);
	scanf("%f", & num2);
	scanf("%s", & op);

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("Answer = %f \n",compute_1(host,num1,num2,op));
	exit (0);
}