/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "compute.h"
#include "stdio.h"

float *
add_1_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp-> num1 + argp->num2;

	return &result;
}

float *
sub_1_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;
	result = argp-> num1 - argp->num2;

	return &result;
}

float *
mul_1_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp-> num1 * argp->num2;

	return &result;
}

float *
div_1_svc(values *argp, struct svc_req *rqstp)
{
	static float  result;

	result = argp-> num1 / argp->num2;

	return &result;
}
